backend/addit/urls.py
from django.urls import path
from django.conf import settings

from addit.views import LandingPage, LoginView, LogoutView, QuoteView, custom_page_not_found

app_name = "addit"

urlpatterns = [
    path("", LandingPage.as_view(), name="landing-page"),
    path("quote/<slug:slug>/", QuoteView.as_view(), name="quote-detail"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout")
]

if settings.DEBUG:
    urlpatterns += [path("error/", custom_page_not_found, name="error")]

backend/config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('v1/', include('addit.api_v1.routers')),
    path('', include('addit.urls'))
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns

handler404 = 'addit.views.custom_page_not_found'

backend/addit/models.py
import random

from uuid import uuid4

from django.db import models
from django_extensions.db.fields import AutoSlugField


class VisibleQuotes(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_visible=True)


class Quote(models.Model):
    time_added = models.DateTimeField()
    handle = models.CharField(max_length=16)
    topic = models.CharField(max_length=100, unique=True)
    slug = AutoSlugField(populate_from=["topic"], max_length=255, overwrite=True)
    content = models.TextField(max_length=512)
    uuid = models.UUIDField(blank=True, null=True)
    is_visible = models.BooleanField(default=True)

    objects = models.Manager()
    visible = VisibleQuotes()

    def get_random_quote(self, query=None):
        items = self.__class__.visible.all()
        if query:
            items = items.filter(topic__icontains=query)
        return random.choice(items)

    def filter_by_topic(self, search):
        return self.__class__.visible.filter(topic__icontains=search)

    def filter_by_content(self, search):
        return self.__class__.visible.filter(content__icontains=search)

    def filter_by_handle(self, search):
        return self.__class__.visible.filter(handle__icontains=search)

    def __str__(self):
        return self.content

    def save(self, *args, **kwargs):
        if not self.uuid:
            self.uuid = str(uuid4())
            while self.__class__.objects.filter(uuid=self.uuid).exists():
                self.uuid = str(uuid4())
        super().save(*args, **kwargs)

backend/addit/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView as DjangoLoginView, LogoutView as DjangoLogoutView
from django.db.models.functions import Lower
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.defaults import page_not_found
from django.views.generic import DetailView, ListView

from addit.models import Quote


class RandomQuoteMixin:
    @staticmethod
    def post(*args, **kwargs):
        quote = Quote().get_random_quote()
        return redirect("addit:quote-detail", quote.slug)


class LandingPage(LoginRequiredMixin, RandomQuoteMixin, ListView):
    template_name = "addit/index.html"
    login_url = reverse_lazy("addit:login")
    queryset = Quote.objects.none()

    def get_queryset(self):
        if {"search", "filter"} <= self.request.GET.keys():
            if self.request.GET.get("filter") in ["content", "topic", "handle"]:
                qs_filter = {f'{self.request.GET.get("filter")}__icontains': self.request.GET.get("search")}
                return Quote.visible.filter(**qs_filter).order_by(Lower("topic"))


class LoginView(DjangoLoginView):
    template_name = "addit/login.html"


class LogoutView(DjangoLogoutView):
    next_page = reverse_lazy("addit:landing-page")


class QuoteView(LoginRequiredMixin, RandomQuoteMixin, DetailView):
    template_name = "addit/index.html"

    def get_object(self, queryset=None):
        return get_object_or_404(Quote, slug=self.kwargs.get("slug"))


def custom_page_not_found(request, exception=None):
    return page_not_found(request, exception, template_name="addit/404.html")

backend/addit/templates/addit/base.html
<!DOCTYPE html>{% load static %}{% load plausible %}
<html lang="fi" data-bs-theme="dark">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Addit</title>
    <meta property="og:title" content="Addit"/>
    <meta property="og:description" content="Addit"/>
    <meta property="og:image" content="{{ host_address }}/static/images/logo192_transparent.png"/>
    <meta property="og:url" content="{{ host_address }}"/>

    <script type="text/javascript" src="{% static 'js/bs-color-mode-toggler.js' %}"></script>

    <link rel="manifest" href="{% static 'site.webmanifest' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.ico' %}"/>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
          integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.3.3/pulse/bootstrap.min.css"
          integrity="sha512-obkkQCe89/FCOU2KW0b5uQy371PYlf2myYmsVb9EaDeI2t+ZtSec+uSA8HdHFiiNfcLWA8p+nRM3WSHrQKpwuA=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}"/>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.3/js/bootstrap.bundle.min.js"
            integrity="sha512-7Pi/otdlbbCR+LnW+F7PwFcSDJOuUJB3OxtEHbg4vSMvzvJjde4Po1v4BR9Gdc9aXNUNFVUY+SK51wWT8WF0Gg=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    {% block extrahead %}
    {% endblock %}

</head>
<body>
<div id="mainContainer" class="container">
    {% block content %}
    {% endblock %}
</div>

{% plausible %}

</body>
</html>

backend/addit/templates/addit/index.html
{% extends 'addit/base.html' %}{% load www_extras %}

{% block extrahead %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js"
            integrity="sha512-BNaRQnYJYiPSqHHDb58B0yaPfCu+Wgds8Gp/gU33kqBtgNS4tSPHuGibyoeqMV/TJlSKda6FXzoEyYGjTe+vXA=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"
            integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.14.0/jquery-ui.min.js"
            integrity="sha512-MlEyuwT6VkRXExjj8CdBKNgd+e2H+aYZOCUaCrt9KRk6MlZDOs91V1yK22rwm8aCIsb5Ec1euL8f0g58RKT/Pg=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui-touch-punch/0.2.3/jquery.ui.touch-punch.min.js"
            integrity="sha512-0bEtK0USNd96MnO4XhH8jhv3nyRF0eK87pJke6pkYf3cM0uDIhNJy9ltuzqgypoIFXw3JSuiy04tVk4AjpZdZw=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.14.0/themes/base/jquery-ui.min.css"
          integrity="sha512-F8mgNaoH6SSws+tuDTveIu+hx6JkVcuLqTQ/S/KJaHJjGc8eUxIrBawMnasq2FDlfo7FYsD8buQXVwD+0upbcA=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
{% endblock %}

{% block content %}

    {% include 'snippets/navbar.html' %}

    <div class="card mb-4">
        <div class="card-body">
            <div class="row">
                <div class="col-12 col-sm-4">
                    <div role="toolbar" class="btn-toolbar">
                        <form method="post">
                            {% csrf_token %}
                            <button class="btn btn-outline-primary btn-block btn-lg" style="height: 58px">
                                <i class="fa-solid fa-shuffle me-2"></i>
                                Random
                            </button>
                        </form>
                    </div>
                </div>
                <div class="col mt-2 mt-sm-0">
                    <div class="input-group">
                        <div class="form-floating">
                            <input id="search" type="text" class="form-control form-control-lg"
                                   value="{{ request.GET.search }}" placeholder="Search...">
                            <label for="search">Search...</label>
                        </div>
                        <button data-filter="topic" type="button" class="btn btn-outline-primary doSearch">
                            <i class="fa-solid fa-magnifying-glass me-2"></i>
                            Search by topic
                        </button>
                        <button type="button"
                                class="btn btn-outline-primary dropdown-toggle dropdown-toggle-split"
                                data-bs-toggle="dropdown" aria-expanded="false">
                            <span class="visually-hidden">Toggle Dropdown</span>
                        </button>
                        <ul class="dropdown-menu dropdown-menu-end">
                            <li><a class="dropdown-item doSearch" data-filter="topic">Search by topic</a></li>
                            <li><a class="dropdown-item doSearch" data-filter="handle">Search by author</a></li>
                            <li><a class="dropdown-item doSearch" data-filter="content">Search by content</a></li>
                        </ul>
                    </div>

                </div>
            </div>
        </div>
    </div>

    <script>
        const search = document.querySelector("#search")

        search.addEventListener("keyup", (e) => {
            console.log(e)
            if (e.key === "Enter") {
                window.location.href = `/?search=${search.value}&filter=topic`
            }
        })

        document.querySelectorAll(".doSearch").forEach((e) => {
            e.addEventListener("click", () => {
                if (search.value) window.location.href = `/?search=${search.value}&filter=${e.dataset.filter}`
            })
        })
    </script>

    {% if object_list %}
        <div class="card mb-4">
            <h3 class="card-header">{{ object_list.count }} Search results</h3>
            <div class="card-body">
                <div class="card-text">
                    <div class="list-group">
                        {% for object in object_list %}
                            <a class="list-group-item list-group-item-action"
                               href="{% url 'addit:quote-detail' object.slug %}">{{ object.topic }}
                            </a>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

    {% if not object_list and request.GET.search %}
        <div class="card mb-4">
            <h3 class="card-header">0 Search results</h3>
        </div>
    {% endif %}

    {% if object %}

        <div id="cardContainer">
            <div id="contentCard" class="card mb-4">
                <div class="card-header fs-3">
                    {{ object.topic }}
                </div>
                <div class="card-body pb-0">
                    <div class="card-text">
                        <div class="quote-monospace">
                            {{ object.content|parse_quote|safe|linebreaks }}
                        </div>
                    </div>
                    <p>- {{ object.handle }}
                        {% if object.time_added.year > 1980 %}
                            <small class="ms-2">({{ object.time_added }})</small>
                        {% endif %}
                    </p>
                </div>
            </div>
            <div class="row">
                <div class="col" style="z-index: 1;">
                    <button id="copyButton" class="btn btn-outline-primary copy-buttons mb-2 me-2"
                            title="Copy to clipboard">
                        <i class="fa-regular fa-clipboard me-2"></i> Copy card to clipboard
                    </button>
                    <button id="imageButton" class="btn btn-outline-primary copy-buttons mb-2"
                            title="Image to new tab">
                        <i class="fa-regular fa-image me-2"></i> Copy card to new tab
                    </button>
                </div>
            </div>
        </div>

        <div class="toast-container  bottom-0 start-0 p-3">
            <div id="alertToast" class="toast" role="alert">
                <div class="toast-header">
                    <strong class="me-auto">Addit</strong>
                    <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
                </div>
                <div class="toast-body">
                    Card copied to clipboard!
                </div>
            </div>
        </div>

        <script>
            $("#contentCard").resizable()

            const mainContainer = document.querySelector("#mainContainer"),
                cardContainer = document.querySelector("#cardContainer"),
                alertToast = new bootstrap.Toast(document.getElementById('alertToast'), {delay: 3000})

            handleResize = (width) => {
                if (width <= 576) {
                    mainContainer.classList.remove("container")
                    cardContainer.classList.add("container")
                } else {
                    mainContainer.classList.add("container")
                    cardContainer.classList.remove("container")
                }
            }

            window.addEventListener('resize', (e) => handleResize(e.target.innerWidth))
            handleResize(window.innerWidth)
        </script>

        <script>
            const card = document.getElementById('contentCard'),
                copyButtons = $(".copy-buttons")

            function dataURItoBlob(dataURI) {
                // This seems to work more reliably than the builtin canvas.toBlob()
                const byteString = atob(dataURI.split(',')[1])
                const mimeString = dataURI.split(',')[0].split(':')[1].split(';')[0]
                const arrayBuffer = new ArrayBuffer(byteString.length)
                const uint8Array = new Uint8Array(arrayBuffer)
                for (let i = 0; i < byteString.length; i++) {
                    uint8Array[i] = byteString.charCodeAt(i)
                }
                return new Blob([arrayBuffer], {type: mimeString})
            }

            copyButtons.each(function () {
                $(this).click(function () {
                    html2canvas(card).then(canvas => {
                        const dataBlob = dataURItoBlob(canvas.toDataURL("image/png"))
                        if ($(this).attr('id') === 'copyButton') {
                            const item = new ClipboardItem({'image/png': dataBlob})
                            navigator.clipboard.write([item])
                                .then(() => alertToast.show())
                                .catch(err => alert(`Failed to copy: ${err}`))
                        } else {
                            window.open(URL.createObjectURL(dataBlob), '_blank')
                        }
                    })
                })
            })
        </script>

    {% endif %}

{% endblock %}

backend/addit/templates/addit/login.html
{% extends 'addit/base.html' %}{% load static %}

{% block content %}


    <div class="d-flex justify-content-center">
        <div class="row">
            <div class="col-md-auto">
                <div class="col text-center">
                    <img src="{% static 'images/logo512_transparent.png' %}" alt="Logo"
                         style="width: 80%; display: inline;">
                    <h2>Sign in</h2>
                </div>

                <div class="col">
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-floating mb-3">
                            <input type="text" name="username" class="form-control" id="floatingInput"
                                   placeholder="Username">
                            <label for="floatingInput">Username</label>
                        </div>
                        <div class="form-floating mb-3">
                            <input type="password" name="password" class="form-control" id="floatingPassword"
                                   placeholder="Password">
                            <label for="floatingPassword">Password</label>
                        </div>
                        <button type="submit" class="form-control btn btn-primary btn-lg">Sign in</button>
                    </form>
                </div>
                <hr/>
                <div class="row">
                    <div class="col quote-monospace">
                        &lt;&commat;T-101&gt; I made this
                    </div>
                    <div class="col-2">
                        <div class="text-end">
                            <a href="https://github.com/T-101/addit">
                                <i class="fa-brands fa-square-github fa-2xl"></i>
                            </a>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>


{% endblock %}

backend/addit/templates/snippets/navbar.html
<nav class="navbar navbar-dark navbar-expand-sm bg-primary mb-4 py-1">{% load static %}
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03"
                aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand quote-monospace" href="{% url 'addit:landing-page' %}">
            <img src="{% static 'images/logo128_transparent.png' %}"
                 class="d-inline-block align-text-top me-1" alt="addit-logo" style="height: 1.5em;"/>
            &lt;Addit&gt;
        </a>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            </ul>
            <ul class="navbar-nav mx-2">
                <li class="nav-item">
                    <form method="post" action="{% url 'addit:logout' %}">
                        {% csrf_token %}
                        <button class="nav-link">
                            <i class="fa-solid fa-circle-user me-2"></i>
                            Logout
                        </button>
                    </form>
                </li>
            </ul>
            <div class="vr text-white d-none d-sm-block"></div>
            <ul class="navbar-nav mx-2">
                <li class="nav-item dropdown bg-primary">
                    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button"
                       aria-haspopup="true" aria-expanded="false"><i class="fas fa-sun"></i></a>
                    <div class="dropdown-menu dropdown-menu-end">
                        <button class="dropdown-item" data-bs-theme-value="light">
                            <i class="fa-solid fa-sun me-2"></i>Light
                        </button>
                        <button class="dropdown-item" data-bs-theme-value="dark">
                            <i class="fa-solid fa-moon me-2"></i>Dark
                        </button>
                        <button class="dropdown-item" data-bs-theme-value="auto">
                            <i class="fa-solid fa-wand-magic-sparkles me-2"></i>Automatic
                        </button>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>